# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/yusuk/DAIKICHI/MIIL/MIIL_VALID_CREATER_GUI.ui'
#
# Created: Thu Apr  4 18:55:38 2019
#      by: pyside2-uic 2.0.0 running on PySide2 5.6.0~a1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(431, 642)
        MainWindow.setMinimumSize(QtCore.QSize(431, 642))
        MainWindow.setMaximumSize(QtCore.QSize(431, 642))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label1 = QtWidgets.QLabel(self.centralwidget)
        self.label1.setEnabled(False)
        self.label1.setGeometry(QtCore.QRect(680, 280, 281, 141))
        self.label1.setText("")
        self.label1.setObjectName("label1")
        self.groupBox1 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox1.setGeometry(QtCore.QRect(10, 80, 211, 81))
        self.groupBox1.setObjectName("groupBox1")
        self.pushButton1 = QtWidgets.QPushButton(self.groupBox1)
        self.pushButton1.setGeometry(QtCore.QRect(10, 17, 93, 51))
        self.pushButton1.setObjectName("pushButton1")
        self.pushButton2 = QtWidgets.QPushButton(self.groupBox1)
        self.pushButton2.setEnabled(False)
        self.pushButton2.setGeometry(QtCore.QRect(110, 17, 93, 51))
        self.pushButton2.setObjectName("pushButton2")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(290, 170, 131, 421))
        self.groupBox.setObjectName("groupBox")
        self.listWidget3 = QtWidgets.QListWidget(self.groupBox)
        self.listWidget3.setGeometry(QtCore.QRect(10, 20, 111, 261))
        self.listWidget3.setObjectName("listWidget3")
        self.pushButton9 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton9.setGeometry(QtCore.QRect(10, 320, 111, 28))
        self.pushButton9.setObjectName("pushButton9")
        self.pushButton8 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton8.setGeometry(QtCore.QRect(10, 290, 111, 28))
        self.pushButton8.setObjectName("pushButton8")
        self.pushButton12 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton12.setGeometry(QtCore.QRect(10, 350, 111, 28))
        self.pushButton12.setObjectName("pushButton12")
        self.pushButton14 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton14.setGeometry(QtCore.QRect(10, 380, 111, 28))
        self.pushButton14.setObjectName("pushButton14")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(150, 170, 131, 421))
        self.groupBox_2.setObjectName("groupBox_2")
        self.listWidget2 = QtWidgets.QListWidget(self.groupBox_2)
        self.listWidget2.setGeometry(QtCore.QRect(10, 20, 111, 261))
        self.listWidget2.setObjectName("listWidget2")
        self.pushButton6 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton6.setGeometry(QtCore.QRect(10, 290, 111, 28))
        self.pushButton6.setObjectName("pushButton6")
        self.pushButton7 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton7.setGeometry(QtCore.QRect(10, 320, 111, 28))
        self.pushButton7.setObjectName("pushButton7")
        self.pushButton11 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton11.setGeometry(QtCore.QRect(10, 350, 111, 28))
        self.pushButton11.setObjectName("pushButton11")
        self.pushButton13 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton13.setGeometry(QtCore.QRect(10, 380, 111, 28))
        self.pushButton13.setObjectName("pushButton13")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 170, 131, 421))
        self.groupBox_3.setObjectName("groupBox_3")
        self.listWidget1 = QtWidgets.QListWidget(self.groupBox_3)
        self.listWidget1.setGeometry(QtCore.QRect(10, 20, 111, 261))
        self.listWidget1.setObjectName("listWidget1")
        self.pushButton4 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton4.setGeometry(QtCore.QRect(10, 290, 111, 28))
        self.pushButton4.setObjectName("pushButton4")
        self.pushButton5 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton5.setGeometry(QtCore.QRect(10, 320, 111, 28))
        self.pushButton5.setObjectName("pushButton5")
        self.pushButton10 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton10.setGeometry(QtCore.QRect(10, 350, 111, 28))
        self.pushButton10.setObjectName("pushButton10")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 10, 411, 61))
        self.groupBox_4.setObjectName("groupBox_4")
        self.pushButton3 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton3.setGeometry(QtCore.QRect(310, 20, 93, 28))
        self.pushButton3.setObjectName("pushButton3")
        self.lineEdit1 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit1.setEnabled(False)
        self.lineEdit1.setGeometry(QtCore.QRect(10, 20, 291, 20))
        self.lineEdit1.setObjectName("lineEdit1")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 431, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MIIL VALID CREATER", None, -1))
        self.groupBox1.setTitle(QtWidgets.QApplication.translate("MainWindow", "PICTURE", None, -1))
        self.pushButton1.setText(QtWidgets.QApplication.translate("MainWindow", "SHOW", None, -1))
        self.pushButton2.setText(QtWidgets.QApplication.translate("MainWindow", "HIDE", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("MainWindow", "VALID", None, -1))
        self.pushButton9.setText(QtWidgets.QApplication.translate("MainWindow", "TO FILE", None, -1))
        self.pushButton8.setText(QtWidgets.QApplication.translate("MainWindow", "TO TRAIN", None, -1))
        self.pushButton12.setText(QtWidgets.QApplication.translate("MainWindow", "SORT", None, -1))
        self.pushButton14.setText(QtWidgets.QApplication.translate("MainWindow", "CHECK PIC", None, -1))
        self.groupBox_2.setTitle(QtWidgets.QApplication.translate("MainWindow", "TRAIN", None, -1))
        self.pushButton6.setText(QtWidgets.QApplication.translate("MainWindow", "TO VALID", None, -1))
        self.pushButton7.setText(QtWidgets.QApplication.translate("MainWindow", "TO FILE", None, -1))
        self.pushButton11.setText(QtWidgets.QApplication.translate("MainWindow", "SORT", None, -1))
        self.pushButton13.setText(QtWidgets.QApplication.translate("MainWindow", "CHECK PIC", None, -1))
        self.groupBox_3.setTitle(QtWidgets.QApplication.translate("MainWindow", "FILE", None, -1))
        self.pushButton4.setText(QtWidgets.QApplication.translate("MainWindow", "TO TRAIN", None, -1))
        self.pushButton5.setText(QtWidgets.QApplication.translate("MainWindow", "TO VALID", None, -1))
        self.pushButton10.setText(QtWidgets.QApplication.translate("MainWindow", "SORT", None, -1))
        self.groupBox_4.setTitle(QtWidgets.QApplication.translate("MainWindow", "PARAMETER FILE", None, -1))
        self.pushButton3.setText(QtWidgets.QApplication.translate("MainWindow", "OPEN", None, -1))

